import { chromium } from 'playwright';
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1440,height:900},userAgent:UA});
await p.goto('https://www.baincapital.com/',{waitUntil:'domcontentloaded',timeout:90000}); await p.waitForTimeout(2500); try { await p.click('.agree-button',{timeout:1500}); } catch {}
let prev=''; const t0=Date.now();
for (let i=0;i<120;i++){ const r=await p.evaluate(()=>{const cur=[...document.querySelectorAll('.banner-tanagram-slider .banner-slide')].findIndex(s=>s.classList.contains('slick-current')); const nav=[...document.querySelectorAll('.banner-nav-slider .slide-single')].findIndex(s=>s.classList.contains('slick-current')); const line=document.querySelector('.banner-nav-slider .slick-current .anim')?.style.width; const act=[...document.querySelectorAll('.slide-bg')].findIndex(g=>g.classList.contains('active-slide')); return `slide ${cur} nav ${nav} tangram ${act}`+' line '+line;}); if(r.split(' line')[0]!==prev){console.log(((Date.now()-t0)/1000).toFixed(1)+'s',r); prev=r.split(' line')[0];} await p.waitForTimeout(250);} 
console.log('--- people bg slideshow');
await p.evaluate(()=>window.scrollTo(0,5300)); await p.waitForTimeout(2000); prev=''; const t1=Date.now();
for (let i=0;i<100;i++){ const r=await p.evaluate(()=>{const im=document.querySelector('.site-bg-image'); const s=getComputedStyle(im); const kids=[...im.querySelectorAll('*')].map(e=>e.tagName+'.'+String(e.className).slice(0,30)+' op'+getComputedStyle(e).opacity+' '+(e.currentSrc||e.src||getComputedStyle(e).backgroundImage||'').split('/').pop().slice(0,30)); const cap=[...document.querySelectorAll('.people-breadcrumb-single')].filter(e=>getComputedStyle(e).opacity>0&&e.getBoundingClientRect().height>0).map(e=>e.innerText.replace(/\s+/g,' ').slice(0,60)); return 'bg '+s.backgroundImage.split('/').pop().slice(0,40)+' op'+s.opacity+' kids '+kids.join(';').slice(0,200)+' | caps '+cap.join(' || ');}); if(r!==prev){console.log(((Date.now()-t1)/1000).toFixed(1)+'s',r); prev=r;} await p.waitForTimeout(300);} 
await b.close();
